version: "3.7"

services:

  web01:
    build:
      context: ./
      dockerfile: ./resources/dockerfiles/Dockerfile-nginx1
    
    ports:
      - 80
    networks:
      - webnetwork

  web02:
    build:
      dockerfile: ./resources/dockerfiles/Dockerfile-nginx2
    ports:
      - 80
    networks:
      - webnetwork

  web:
    build:
      dockerfile: ./resources/dockerfiles/Dockerfile-haproxy
    ports:
      - 80:80
    networks:
      - webnetwork

networks:
  webnetwork:
    driver: bridge
